

```{r}
library(ggcorrplot)
ggcorrplot(cor(y_cor), 
           lab = T,
           tl.cex = 15,
           title = "Pearson’s Correlation Analysis between \n BMI, Covariates and Physical Activity") + 
  labs(caption = 'Note. RIDAGEYR - Age in years at screening.') + 
  theme(plot.title = element_text(size = 20),
        plot.caption = element_text(size = 15))
```

# combine with library(gridExtra)
```{r}
library(ggcorrplot)
vec = list('data22','data26','data31','data36')
lapply(vec, function(i){
  data = get(i) %>% select(-rawid,-Age,-Gender)
  ggcorrplot(cor(data, method = 'spearman'), 
             # hc.order = TRUE,
             type = "lower",
             p.mat = cor_pmat(data),
             title = i)
})
```




# https://cran.r-project.org/web/packages/corrplot/vignettes/corrplot-intro.html


```{r}
library(corrplot)
corrplot(cor(data),
         # addCoef.col = T,
         method = 'color',
         type = 'upper',
         order = 'hclust',
         p.mat = cor.mtest(data, conf.level = .95)$p
)
```


