# grid.arrange common legend

```{r}
# scale = F
if(F){
  pca_model = prcomp(MINdata %>% select(-SEQN),
                     scale. = F)
  save(pca_model,file= 'pca_model_unscale.rda')
}




load(file = 'pca_model_unscale.rda')
pcscore = data.frame(SEQN = MINdata$SEQN, pca_model$x)

gs = lapply(1:3, function(i) {
  id_high = pcscore$SEQN[which(pcscore[,paste0('PC',i)] == max(pcscore[,paste0('PC',i)]))]
  id_low = pcscore$SEQN[which(pcscore[,paste0('PC',i)] == min(pcscore[,paste0('PC',i)]))]
  tmp_high = MINdata %>% filter(SEQN %in% id_high) %>% select(-SEQN) %>% t %>% as.data.frame()
  tmp_low = MINdata %>% filter(SEQN %in% id_low) %>% select(-SEQN) %>% t %>% as.data.frame()
  tmp_average = MINdata %>% select(-SEQN) %>% colMeans() %>% as.data.frame()
return(
  ggplot() +
    geom_line(data = tmp_high, aes(x = 1:1440/60, y =  unlist(tmp_high), color = paste0('Subject with the Highest PC',i,' Scores'))) + 
    geom_line(data = tmp_low, aes(x = 1:1440/60, y = unlist(tmp_low), color = paste0('Subject with the Lowest PC',i,' Scores')))  + 
    geom_line(data = tmp_average, aes(x = 1:1440/60, y =  unlist(tmp_average), color = paste0('Averaged Subject Scores')))  +
    labs(x='',y= '') +
    scale_colour_manual(name="", values = c('black','red','green'))
)
})
grid_arrange_shared_legend <- function(...) {
    plots <- list(...)
    g <- ggplotGrob(plots[[1]] + theme(legend.position="bottom"))$grobs
    legend <- g[[which(sapply(g, function(x) x$name) == "guide-box")]]
    lheight <- sum(legend$height)
    grid.arrange(
        do.call(arrangeGrob, lapply(plots, function(x)
            x + theme(legend.position="none"))),
        legend,
        ncol = 1,
        left = 'Averaged Daily Activity Scores',
        bottom = 'Time of Day',
        heights = unit.c(unit(1, "npc") - lheight, lheight))
}

do.call(grid_arrange_shared_legend,gs)
```











# How to add legend to geom_smooth in ggplot in R

https://stackoverflow.com/questions/36276240/how-to-add-legend-to-geom-smooth-in-ggplot-in-r
```{r}


# NHANES

rm(list = ls())
library(caret)
library(gridExtra)
load(file = 'analyticData.rda')
res_RMSE = c()
res_Rsquared = c()
if(F){
  for(i in 1:50){
    PCnames = paste('PC',1:i,sep = '')
    train.control <- trainControl(method = "cv", number = 10)
    dat = analyticData[,c('RIDAGEYR','Race','Gender','BMI',PCnames)]
    model <- caret::train(BMI ~., data = dat, method = "lm",
                          trControl = train.control)
    res_RMSE = c(res_RMSE, model$results$RMSE)
    res_Rsquared = c(res_Rsquared, model$results$Rsquared)
    
  }
  save(res_RMSE,res_Rsquared, file = 'CV_50PCs.rda')
}

load(file = 'CV_50PCs.rda')
g1 = ggplot(data.frame(res_RMSE)) + 
  aes(x = 1:length(res_RMSE), y = res_RMSE) +
  geom_line(aes(color = 'Original RMSE Loss')) +
  geom_smooth(se = TRUE, method =  'auto', aes(color = 'Smoothed RMSE Loss')) +
  labs(x = 'Number of Principal Components Used in Cross-Validation',y = 'Root Mean Square Error ') +
  scale_colour_manual(name="Legend", values=c("blue", "red"))

g2 = ggplot(data.frame(res_Rsquared)) + 
  aes(x = 1:length(res_Rsquared), y = res_Rsquared) +
  geom_line(aes(color = 'Original RMSE Loss'))+
  geom_smooth(se = TRUE, method =  'auto', aes(color = 'Smoothed RMSE Loss')) + 
  labs(x = 'Number of Principal Components Used in Cross-Validation',y = 'R-squared') +
  scale_colour_manual(name="Legend", values=c("blue", "red"))

which(res_RMSE==min(res_RMSE))
which(res_Rsquared==max(res_Rsquared))
grid.arrange(g1,g2)

```


# grid.arrange layout

```{r}
temp = pca_model$rotation %>% data.frame()

gs = lapply(1:8, function(i) {
  ggplot(temp) + 
    aes(x = 1:nrow(temp)/60,y = unlist(temp[,i])) + 
    geom_line() +
    labs(x = "Time of Day", y = paste0("Loadings on PC",i)) +
    theme(axis.title.y = element_text(size = rel(0.9)))
})
library(gridExtra)
do.call(grid.arrange,c(gs,nrow = 3))
```


# How do I generate a histogram for each column of my table?

https://stackoverflow.com/questions/35372365/how-do-i-generate-a-histogram-for-each-column-of-my-table/35373419
```{r}
ggplot(gather(data), aes(value)) + 
  geom_histogram(bins = 10) + 
  facet_wrap(~key, scales = 'free_x')
```


